# backend-agent/docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-web-developer-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OPENHANDS_WORKSPACE=/opt/workspace
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - OPENHANDS_SERVICE_URL=http://openhands:3000/api/modify
    env_file:
      - .env
    volumes:
      - ./workspace:/opt/workspace
      - ./:/app
    depends_on:
      - openhands

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.13
    container_name: openhands-service
    ports:
      - "3000:3000"
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/app/config.toml # Mount your config.toml
    extra_hosts:
      - "host.docker.internal:host-gateway"
